# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

# This can be configured to run on a cron schedule
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Fetch up to date reports
      run: npm fetch
    
    - name: Commit and push resulting changes
      # feel free to change the username and password here
      run: |
        git config --global user.name "Alex Colby"
        git config --global user.email "alexanderdcolby@gmail.com"

        git add -A
        git commit -m "latest report data fetched"
        git push
